#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor HDMI1 -d 1 2 3 4 5 6
bspc monitor eDP1 -d 7 

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

#bspc config normal_border_color "#313244"
bspc config normal_border_color "#6495ED"
bspc config focused_border_color "#6495ED"

bspc config top_padding 50 # Cambiado a 0 para eDP1
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

# Deshabilitar botones de minimizar, maximizar y cerrar

# ~/.config/polybar/launch.sh 
xrandr --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --output eDP1 --mode 1366x768 --pos 1920x0
sh $HOME/.fehbg &
killall -q polybar

for m in $(polybar --list-monitors | cut -d":" -f1); do
	if [ "$m" = "HDMI1" ]; then
	    MONITOR=$m polybar --reload bar1 &
		MONITOR=$m polybar --reload bar2 &
		MONITOR=$m polybar --reload bar3 &
		MONITOR=$m polybar --reload bar4 &
		MONITOR=$m polybar --reload bar5 &
		MONITOR=$m polybar --reload bar6 &
	else
	    MONITOR=$m polybar --reload bar1 &
		MONITOR=$m polybar --reload bar2 &
		MONITOR=$m polybar --reload bar3 &
		MONITOR=$m polybar --reload bar4 &
		MONITOR=$m polybar --reload bar5 &
		MONITOR=$m polybar --reload bar6 &
	fi
done

picom &
killall -q flameshot
flameshot &
pgrep -xq nm-applet || nm-applet &
setxkbmap latam &
touchpad_config --enable &
